project:
  type: website
  output-dir: docs
  render:
    - index.qmd
              
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 675
    file: index.qmd
 
format: 
  html:
    theme: yeti
    scss: styles.css
    link-external-newwindow: true
    
   



