project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - slides.qmd
              
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 675
    file: index.qmd
    right:
      - text: Slides 
        file: slides.qmd
 
format: 
  html:
    theme: yeti
    scss: styles.css
    link-external-newwindow: true
    
   



